### ISSUE TITLE
Multiple cores/snowfall

### ISSUE THREAD

**Issue by jimr1603** [FunWithR/MonteCarlo#9]
Hi

I got an error that it couldn't find a value or function, with ncpu=2. I manually loaded snowfall and the same call worked. I believe the package needs a "require(snowfall)" before running code based on multiple processors.

**Comment by theclue** [comment]
I suffer the same issue. with this error: Unknown/unfound variable <myvar> in export. (local=TRUE)

**Comment by FunWithR** [comment]
New package version 1.0.6 is on its way to CRAN. Bug is fixed, Occured because snow was listed as an import, but snowfall has snow in DEPENDS.
